name: Developer to Main PR

on:
  push:
    branches:
      - developer

jobs:
  pr-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Pull Request to main
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          pr_label: "release, automated pr"
          pr_title: "PR automático da branch developer para main"
          pr_body: "Este PR foi criado automaticamente para sincronizar as alterações da branch developer com a branch main."