name: Feature to Developer PR

on:
  push:
    branches:
      - 'feature/**'

jobs:
  build-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: npm install
        run: npm install
    
      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Create Pull Request to developer
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "developer"
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          pr_label: "feature,automated-pr"
          pr_title: "PR automático da branch feature para developer"
          pr_body: "Este PR foi criado automaticamente para sincronizar as alterações da branch feature com a branch developer."