name: Feature Branch CI and PR

on:
  push:
    branches:
      - 'feature/**'

jobs:
  build-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Create Pull Request to developer
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: developer
          branch: ${{ github.ref_name }}
          title: 'Feature: ${{ github.ref_name }}'
          body: 'PR automático da branch feature para developer'
          draft: false