name: Test deployment

on:
  push:
    branches:
      - main
      - developer
      - "feature/**"
  pull_request:
    branches:
      - main
      - developer
      - "feature/**"

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest

    steps:
      # Faz checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # Configura Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # Instala dependências
      - name: Install dependencies
        run: npm ci

      # Testa build
      - name: Test build
        run: npm run build

      # Passo extra só para ver logs
      - name: Hello world log
        run: echo "Workflow disparou com sucesso!"